name: PKG-PUBLISH
on: 
  workflow_dispatch:
    inputs:
      tag:
        description: "Version to be published"
        required: true 
      description:
        description: "Version update Message"
        type: string

    tags:
    - "[0-9]+.[0-9]+.[0-9]"
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 
    defaults:
      run:
        working-directory: .

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: 6.0.x 

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.1.1

    - name: Check out Code
      uses: actions/checkout@v3
      with:
         fetch-depth: 0   

    - name: Pack
      run: dotnet pack Acme.BookStore.sln --configuration Release /p:Version=${{ inputs.tag }}  --output .

    - name: Push
      run: nuget push *.nupkg -Source https://nuget.pkg.github.com/preetham-p-m/index.json -ApiKey ${NUGET_TOKEN} -Description ${{ inputs.description }}
      env:
        NUGET_TOKEN: ${{ secrets.ABP_BOOK_APP_TOKEN  }}